local-api:
  url: https://dapi.kakao.com/v2/local/search/keyword.json
  apikey: 7822edec9750a048bde7fa98f9e796a3

map-url-info:
  base_url: https://map.kakao.com/link
  items:
    - name: map
      url: /map
    - name: to
      url: /to
    - name: roadview
      url: /roadview
    - name: search
      url: /search
