Server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/AED
    username: pjh
    password: pjh
    driver-class-name: org.h2.Driver
  messages:
    basename: messages
  security:
    user:
      name: pjh
      password: pjh
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    logging.level:
      org.hibernate.SQL: debug