Server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/webflux
    username: pjh
    password: pjh
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

    logging.level:
      org.hibernate.SQL: debug
# org.hibernate.type: trace
