server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/clothes
    username: daou
    password: daou
    driver-class-name: org.h2.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: none
    properties:
      hibernate:
       # show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  data:
    web:
      pageable:
        default-page-size: 9
#log:
#  path: /log/was/
#  name: test_shopping_mall.log
#  pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] %msg %n"
#  appender: dailyRollingFileAppender

logging:
  level:
    kr.co.daou: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: debug
    org.hibernate.type: trace

