server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/clothes
    username: daou
    password: daou
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
       # show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

#log:
#  path: /log/was/
#  name: test_shopping_mall.log
#  pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] %msg %n"
#  appender: dailyRollingFileAppender

logging:
  level:
    kr.co.daou: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: debug
    org.hibernate.type: trace
