server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
#    url: jdbc:h2:mem:clothes
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
    sql-script-encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: none
    properties:
      hibernate:
       # show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
      default_batch_fetch_size: 100
    open-in-view: false

  data:
    web:
      pageable:
        default-page-size: 9

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile
          facebook:
            client-id:
            client-secret:
            scope:
              - email
              - public_profile
          naver:
            client-id:
            client-secret:
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보 json으로받는데 response라는 키값으로 리턴받음
log:
  path: /log/was/
  name: test_shopping_mall.log
  pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] %msg %n"
  appender: dailyRollingFileAppender

logging:
  level:
    kr.co.daou: info
    org.springframework: INFO
    org.hibernate.SQL: debug
    org.hibernate.type: trace


springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /product/**



