insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 1 , '/images/outer01.jpg', 'outer01' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 2 , '/images/outer02.jpg', 'outer02' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 3 , '/images/outer03.jpg', 'outer03' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 4 , '/images/outer04.webp', 'outer04' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 5 , '/images/outer05.jpg', 'outer05' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 6 , '/images/outer06.jpg', 'outer06' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 7 , '/images/outer07.jpg', 'outer07' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 8 , '/images/outer08.jpg', 'outer08' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 9 , '/images/outer09.jpg', 'outer09' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 10 , '/images/outer10.jpg', 'outer10' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 11 , '/images/pants01.jpg', 'pants01' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 12 , '/images/pants02.jpg', 'pants02' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 13 , '/images/pants03.webp', 'pants03' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 14 , '/images/pants04.jpg', 'pants04' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 15 , '/images/pants05.jpg', 'pants05' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 16 , '/images/pants06.jpg', 'pants06' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 17 , '/images/pants07.jpg', 'pants07' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 18 , '/images/pants08.jpg', 'pants08' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 19 , '/images/pants09.webp', 'pants09' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 20 , '/images/pants10.jpg', 'pants10' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 21 , '/images/top01.jpg', 'top01' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 22 , '/images/top02.jpg', 'top02' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 23 , '/images/top09.jpg', 'top09' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 24 , '/images/top04.jpg', 'top04' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 25 , '/images/top05.jpg', 'top05' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 26 , '/images/top06.jpg', 'top06' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 27 , '/images/top07.jpg', 'top07' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 28 , '/images/top08.jpg', 'top08' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 29 , '/images/top03.webp', 'top03' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 30 , '/images/top10.jpg', 'top10' , 1);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 31, '/images/top11.jpg', 'top11' , 0);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 32, '/images/top12.jpg', 'top12' , 0);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 33, '/images/top13.jpg', 'top13' , 0);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 34, '/images/top14.jpg', 'top14' , 0);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 35, '/images/top15.jpg', 'top15' , 0);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 36, '/images/outer11.jpg', 'outer11' , 0);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 37, '/images/outer12.jpg', 'outer12' , 0);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values(38, '/images/outer13.jpg', 'outer13' , 0);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values(39, '/images/outer14.jpg', 'outer14' , 0);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values(40, '/images/outer15.jpg', 'outer15' , 0);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 41, '/images/pants11.jpg', 'pants11' , 0);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values( 42, '/images/pants12.jpg', 'pants12' , 0);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values(43, '/images/pants13.jpg', 'pants13' , 0);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values(44, '/images/pants14.jpg', 'pants14' , 0);
insert into TB_ATT_IMG(ATT_IMG_ID, IMAGE_PATH, IMAGE_NICKNAME, ENABLED) values(45, '/images/pants15.jpg', 'pants15' , 0);
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, MATERIAL) values(1, 1, 'O001', 3000, SYSDATE, '부드러운 느낌의 헤링본패턴',  '하벤즈 헤링본 울 로브 코트', 134000, 5, '울');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, MATERIAL) values(2, 2, 'O001', 3000, SYSDATE, '양털 바버 패딩 자켓',  '털빠짐 없는 카라의 리얼양털로 퀄리티 높인 패딩자켓!', 99000, 5, '양털');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, MATERIAL) values(3, 3, 'O001', 3000, SYSDATE, '탈부착 가능한 카라의 리얼덤블!',  '덤블 카라 덕다운 패딩 점퍼', 120000, 5, '오리털');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, MATERIAL) values(4, 4, 'O001', 3000, SYSDATE, '빈티지하면서 메니쉬한 항공 점퍼!',  '프로슨 덤블 항공 점퍼', 114000, 5, '울');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, MATERIAL) values(5, 5, 'O001', 3000, SYSDATE, '벨트 세트로 부해보이지 않고 세련된 핏으로 착용할 수 있는 패딩 자켓',  '클래식 바버 패딩 자켓', 100500, 5, '양털');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, MATERIAL) values(6, 6, 'O001', 3000, SYSDATE, '유니크한 디자인으로 소장가치 매우 높은 울 코트입니다 :)',  '발칸 로브 울 코트', 118000, 5, '면');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, MATERIAL) values(7, 7, 'O001', 3000, SYSDATE, '완벽하게 똑 떨어지는 스탠다드핏이 예술 !',  '휴즈 울 더블 코트', 93000, 5, '울');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, MATERIAL) values(8, 8, 'O001', 3000, SYSDATE, '정말 빵빵한 패딩이에용',  '프밍 패딩 점퍼', 67000, 5, '말털');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, MATERIAL) values(9, 9, 'O001', 3000, SYSDATE, '은은하고 무드있는 헤링본 패턴',  '머즈 헤링본 울 자켓', 75000, 5, '울');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, MATERIAL) values(10, 10, 'O001', 3000, SYSDATE, '겉감은 스웨이드, 안감은 양털로 보온성과 부드러운 터치감의 무스탕 자켓',  '버운하프 무스탕 자켓', 92000, 5, '무스탕');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, WAIST_WIDTH ) values(11, 11, 'P001', 3000, SYSDATE, '다른 와이드 슬랙스랑 꼭 비교해보세요!',  '맥스 롱 와이드 슬랙스', 30000, 5, '허리 39, 밑위 28, 허벅지31, 밑단 19, 총길이 102');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, WAIST_WIDTH ) values(12, 12, 'P001', 3000, SYSDATE, 'FW 데일리로 코디하기 딱 좋은 슬랙스 :)',  '크루 슬랙스', 36000, 5, '허리 39, 밑위 28, 허벅지31, 밑단 19, 총길이 102');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, WAIST_WIDTH ) values(13, 13, 'P001', 3000, SYSDATE, '텐션감 좋은 코튼 소재로 편하게 즐겨주세요',  '피치 치노팬츠', 41000, 5, '허리 39, 밑위 28, 허벅지31, 밑단 19, 총길이 102');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, WAIST_WIDTH ) values(14, 14, 'P001', 3000, SYSDATE, '기모+반밴딩+스판으로 겨울 데릴리 슬랙스로 추천합니당',  '벤스 기모 반밴딩 슬랙스', 42000, 5, '허리 39, 밑위 28, 허벅지31, 밑단 19, 총길이 102');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, WAIST_WIDTH ) values(15, 15, 'P001', 3000, SYSDATE, '롱한 와이드핏이 예술이네요 :)',  '마스 롱 와이드 슬랙스', 35000, 5, '허리 39, 밑위 28, 허벅지31, 밑단 19, 총길이 102');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, WAIST_WIDTH ) values(16, 16, 'P001', 3000, SYSDATE, '다른 와이드 슬랙스랑 비교해보세요',  '맥스 롱 와이드 슬랙스', 30000, 5, '허리 39, 밑위 28, 허벅지31, 밑단 19, 총길이 102');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, WAIST_WIDTH ) values(17, 17, 'P001', 3000, SYSDATE, '깔끔한 코튼 팬츠',  '레귤러핏 팬츠', 29000, 5, '허리 39, 밑위 28, 허벅지31, 밑단 19, 총길이 102');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, WAIST_WIDTH ) values(18, 18, 'P001', 3000, SYSDATE, '무릎 구제후 원단을 덧대었어용',  '5cm jean', 35000, 5, '허리 39, 밑위 28, 허벅지31, 밑단 19, 총길이 102');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, WAIST_WIDTH ) values(19, 19, 'P001', 3000, SYSDATE, '유니크한 색감에 착용감은 또 얼마나 편하게용',  '페이즈 반벤딩 슬랙스', 35000, 5, '허리 39, 밑위 28, 허벅지31, 밑단 19, 총길이 102');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, WAIST_WIDTH ) values(20, 20, 'P001', 3000, SYSDATE, '세련미 넘치는 컬러로 제작된 스판성 좋은 슬랙스:)',  'PN 7400 스판 슬랙스', 26000, 5, '허리 39, 밑위 28, 허벅지31, 밑단 19, 총길이 102');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, SHOULDER_WIDTH ) values(21, 21, 'T001', 3000, SYSDATE, '캐주얼한 파스텔 컬러에 양기모로 따뜻해요',  '파스텔 양기모 맨투맨', 28000, 5, '어깨 64, 가슴 63, 팔길이 57, 총기장 68');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, SHOULDER_WIDTH ) values(22, 22, 'T001', 3000, SYSDATE, '얼굴까지 화사해보이는 컬러에 트위스트 짜임',  '스노우 꽈배기 울 니트', 51000, 5, '어깨 64, 가슴 63, 팔길이 57, 총기장 68');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, SHOULDER_WIDTH ) values(23, 23, 'T001', 3000, SYSDATE, '편안하게 즐길수 있는 니트 집업',  '레터 울 니트 집업', 49000, 5, '어깨 64, 가슴 63, 팔길이 57, 총기장 68');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, SHOULDER_WIDTH ) values(24, 24, 'T001', 3000, SYSDATE, '편하게 여기저기 입기 좋은 피그먼트 맨투맨',  '게트 피그먼트 기모 맨투맨', 32000, 5, '어깨 64, 가슴 63, 팔길이 57, 총기장 68');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, SHOULDER_WIDTH ) values(25, 25, 'T001', 3000, SYSDATE, '믹스된 묘한 컬러감이 예쁜 터틀넥니트',  '믹스 터틀넥 울 니트', 37000, 5, '어깨 64, 가슴 63, 팔길이 57, 총기장 68');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, SHOULDER_WIDTH ) values(26, 26, 'T001', 3000, SYSDATE, '베이직에 퀄리티를 담았어요',  '프링 울 하찌 니트', 35000, 5, '어깨 64, 가슴 63, 팔길이 57, 총기장 68');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, SHOULDER_WIDTH ) values(27, 27, 'T001', 3000, SYSDATE, '깔끔하고 캐주얼한 웜업',  '양기모띠 후드', 35000, 5, '어깨 64, 가슴 63, 팔길이 57, 총기장 68');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, SHOULDER_WIDTH ) values(28, 28, 'T001', 3000, SYSDATE, '후리스 소재로 겨울에 입기 좋아요',  '그래비티 후리스 후드', 32300, 5, '어깨 64, 가슴 63, 팔길이 57, 총기장 68');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, SHOULDER_WIDTH ) values(29, 29, 'T001', 3000, SYSDATE, '1+1 프로젝트, 코디에 맞춰서 번갈아 입어주세요',  '1+1 기모 라운드 티셔츠', 26000, 5, '어깨 64, 가슴 63, 팔길이 57, 총기장 68');
insert into TB_PRODUCT_MASTER(PRODUCT_MASTER_ID, ATT_IMG_ID, PRODUCT_TYPE, DELIVERY_FEE, REGISTRATION_DATE, EXPLAIN, NAME, PRICE, STOCK, SHOULDER_WIDTH ) values(30, 30, 'T001', 3000, SYSDATE, '언제 어디서든 편하게 입기 좋아요',  '제리 니트 맨투맨', 31000, 5, '어깨 64, 가슴 63, 팔길이 57, 총기장 68');
insert into TB_MEMBER values(1, 'admin', sysdate, '관리자', '$2a$10$0xSWv4MNwBk0mFcm1Cv50u3rJn8cqpvSuxe8a.9HujR914dOU.IZa', sysdate, 'ADMIN');