Server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  datasource:
    url: jdbc:h2:tcp://localhost/~/map
    username: kakaoapitest
    password: kakaoapitest
    driver-class-name: org.h2.Driver
#  security:
#    user:
#      name: pjh
#      password: pjh
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    logging.level:
      org.hibernate.SQL: debug
